import '../common/lib/ultisite.js';
import { isAdmin, settings } from '../common/lib/ultisite.js';
import '../common/routes.js';
import '../common/schemas.js';
import '../common/search.js';
import '../common/teams.js';
import './accessRules.js';
import './address.js';
import './admin.js';
import './authorization.js';
import './contentVersions.js';
import './database.js';
import './events.js';
import './export.js';
import './files.js';
import './imageHelper.js';
import './injections.js';
import './mail.js';
import { Mail, renderMailTemplate } from './mail.js';
import './mailinglist.js';
import './main.js';
import './manifest.json.js';
import './migrations.js';
import './msxmltiles.js';
import './observers.js';
import './offline.js';
import './practices.js';
import './publishing.js';
import './static.js';
import './statistics.js';
import './teams.js';
import './tournament.js';
import './user.js';
import './wikipage.js';
import './wikitranslator.js';
import { configureHat } from 'meteor/ultisite:hatinfo';

configureHat({ settings, Mail, renderMailTemplate, isAdmin });
